reviews:
  profile: assertive
  review_details: true
  tools:
    emberTemplateLint:
      enabled: true
    flake8:
      enabled: true
    luacheck:
      enabled: true
    markdownlint:
      enabled: true
    phpcs:
      enabled: true
    eslint:
      enabled: true
    ast-grep:
      enabled: true
